// Auto-generated by wasm-types
export default async function init(imports = {}) {
  const response = await fetch("./wasm_demo.wasm");
  const { instance } = await WebAssembly.instantiateStreaming(response, imports);
  return instance.exports;
}
