// Auto-generated by wasm-types
declare module "./wasm_demo.wasm" {
  export interface Exports {
    add(arg0: number, arg1: number): number;
    multiply(arg0: number, arg1: number): number;
    greet(arg0: number, arg1: number): void;
    __malloc(arg0: number): number;
    __free(arg0: number, arg1: number): void;
    memory: WebAssembly.Memory;
  }
  const init: (imports?: WebAssembly.Imports) => Promise<Exports>;
  export default init;
}
